### GET ALL CONTACTS
GET http://localhost:8080/contacts


### GET CONTACT BY ID
# Replace the ID below with a real ID from your MongoDB collection
GET http://localhost:8080/contacts/65f2c4198765432101234567


### CREATE CONTACT
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Arsenio",
    "lastName": "Hall",
    "email": "ahall@test.com",
    "favoriteColor": "Blue",
    "birthday": "02/12/1956"
}


### UPDATE CONTACT
# Replace the ID below with the ID returned from the POST request above
PUT http://localhost:8080/contacts/65f2c4198765432101234567 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Arsenio",
    "lastName": "Hall",
    "email": "arsenio.hall@newmail.com",
    "favoriteColor": "Purple",
    "birthday": "02/12/1956"
}


### DELETE CONTACT
# Replace the ID below with a real ID you want to remove
DELETE http://localhost:8080/contacts/65f2c4198765432101234567 HTTP/1.1


# --- RENDER LINKS ---

### GET ALL CONTACTS (RENDER)
GET https://your-app-name.onrender.com/contacts